name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create virtual environment
      run: python3 -m venv venv

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
