name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Create virtual environment
      run: python3 -m venv /tmp/venv

    - name: Install Python dependencies
      run: |
        source /tmp/venv/bin/activate
        pip install -r requirements.txt

    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
      with:
        source: mentorship/templates
        destination: _site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
